<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MSI" failures="1" tests="8" name="Surefire test" time="0.042" errors="0" timestamp="2024-06-14T09:58:53 ICT">
  <testcase classname="BankAccountTest" name="testAddInterest" time="0.002"/>
  <testcase classname="BankAccountTest" name="testDeposit" time="0.0"/>
  <testcase classname="BankAccountTest" name="testInitialBalance" time="0.0"/>
  <testcase classname="BankAccountTest" name="testOverdraft" time="0.001"/>
  <testcase classname="BankAccountTest" name="testTransactionHistory" time="0.0"/>
  <testcase classname="BankAccountTest" name="testWithdraw" time="0.0"/>
  <testcase classname="BankAccountTest" name="testWithdrawExceedingOverdraft" time="0.0"/>
  <testcase classname="BankAccountTest" name="testWithdrawMoreThanBalance" time="0.0">
    <failure type="java.lang.AssertionError" message="Withdrawal should fail when exceeding overdraft limit expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Withdrawal should fail when exceeding overdraft limit expected [false] but found [true]
at BankAccountTest.testWithdrawMoreThanBalance(BankAccountTest.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testWithdrawMoreThanBalance -->
</testsuite> <!-- Surefire test -->
